# Generated by Django 4.1.7 on 2023-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("content", models.CharField(max_length=999)),
                ("date", models.CharField(max_length=64)),
                ("time", models.CharField(max_length=64)),
                ("likes", models.IntegerField(max_length=999)),
            ],
        ),
    ]
