# Generated by Django 4.1.7 on 2023-08-10 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_time_alter_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user", name="followers", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user", name="following", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post", name="likes", field=models.IntegerField(default=0),
        ),
    ]
