# Generated by Django 4.1.7 on 2023-08-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="username",),
    ]
