# Generated by Django 4.1.7 on 2023-08-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_remove_post_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="followers",),
        migrations.RemoveField(model_name="user", name="following",),
    ]
