# Generated by Django 4.1.7 on 2023-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_rename_user_post_userperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="likedPosts",
            field=models.ManyToManyField(
                blank=True, related_name="posts_liked", to="network.post"
            ),
        ),
    ]
