# Generated by Django 4.1.7 on 2023-08-22 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_user_likedposts"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="likedPosts",),
        migrations.AddField(
            model_name="post",
            name="usersLiked",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
