# Generated by Django 4.1.7 on 2023-08-22 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0012_alter_post_usersliked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="usersLiked",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
