# Generated by Django 4.1.7 on 2023-08-22 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0013_alter_post_usersliked"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="usersLiked",),
        migrations.AddField(
            model_name="post",
            name="usersLiked",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
