# Generated by Django 4.1.7 on 2023-08-22 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0014_remove_post_usersliked_post_usersliked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="usersLiked",
            field=models.ManyToManyField(
                blank=True, related_name="post_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
